name: Actualizar Partidos
on:
  schedule:
    - cron: '0 8 * * *' # Se ejecuta todos los días a las 8 AM
  workflow_dispatch: # Permite ejecutarlo manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Correr Script
        run: python app.py
      - name: Guardar cambios
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add picks.json
          git commit -m "Auto-actualización de picks"
          git push
